service: python-hello-sls-plugin

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  numpy:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
